// ─── Types ────────────────────────────────────────────────────────────────────

export type ChapterType = "video" | "lecture" | "interactive" | "quiz_only"

export type Chapter = {
  id: number
  title: string
  duration: string
  type: ChapterType
  video_url?: string
  key_concepts: string[]
  practical_example: string
}

export type Course = {
  id: string
  title: string
  level: "débutant" | "intermédiaire" | "avancé"
  duration: string
  chapters_count: number
  icon: string
  description: string
  video_intro: string
  chapters: Chapter[]
}

// ─── Course catalog ───────────────────────────────────────────────────────────

export const COURSES: Course[] = [

  // ══════════════════════════════════════════════════════════════════
  // DÉBUTANT (5 cours)
  // ══════════════════════════════════════════════════════════════════

  {
    id: "introduction-marches",
    title: "Introduction aux marchés financiers",
    level: "débutant",
    duration: "1h",
    chapters_count: 8,
    icon: "🌍",
    description: "Comprendre comment fonctionnent les marchés, les bourses mondiales et les acteurs du marché",
    video_intro: "https://www.youtube.com/embed/ZCFkWDdmXG8",
    chapters: [
      {
        id: 1,
        title: "Qu'est-ce qu'un marché financier ?",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/ZCFkWDdmXG8",
        key_concepts: ["Marché primaire", "Marché secondaire", "Liquidité", "Prix d'équilibre"],
        practical_example: "Quand Apple émet de nouvelles actions pour lever des fonds, c'est le marché primaire. Quand tu achètes des actions AAPL sur ton broker, tu es sur le marché secondaire.",
      },
      {
        id: 2,
        title: "Les grandes bourses mondiales",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["NYSE", "NASDAQ", "Euronext Paris", "Tokyo Stock Exchange", "Heures de trading"],
        practical_example: "Le NYSE ouvre à 9h30 ET. Si tu es en France, c'est 15h30 heure française. C'est pourquoi les marchés US influencent les marchés européens dès l'ouverture.",
      },
      {
        id: 3,
        title: "Les acteurs des marchés",
        duration: "6 min",
        type: "lecture",
        key_concepts: ["Investisseurs particuliers", "Investisseurs institutionnels", "Hedge funds", "Market makers", "Brokers"],
        practical_example: "BlackRock gère 10 000 milliards de dollars. Quand ils décident d'acheter une action, le prix monte immédiatement — c'est le poids des institutionnels.",
      },
      {
        id: 4,
        title: "Actions, obligations, ETF — les différents actifs",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/WEDIj9JBTC8",
        key_concepts: ["Action", "Obligation", "ETF", "Dividende", "Coupon"],
        practical_example: "SPY est un ETF qui réplique le S&P 500. Au lieu d'acheter les 500 actions séparément, tu achètes une seule part SPY qui les contient toutes.",
      },
      {
        id: 5,
        title: "Comment est fixé le prix d'un actif ?",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Offre et demande", "Carnet d'ordres", "Bid/Ask spread", "Market cap"],
        practical_example: "NVIDIA en mars 2024 : la demande explosive sur l'IA a propulsé l'action de $200 à $900 en 6 mois. Le prix reflète l'anticipation des bénéfices futurs.",
      },
      {
        id: 6,
        title: "Les indices boursiers",
        duration: "7 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/3jnKTKRrLhA",
        key_concepts: ["S&P 500", "CAC 40", "Dow Jones", "Pondération", "Benchmark"],
        practical_example: "Le S&P 500 a rapporté en moyenne +10%/an sur 50 ans. Un simple ETF SPY depuis 2010 = +600%. C'est le benchmark que tout le monde essaie de battre.",
      },
      {
        id: 7,
        title: "Les cycles de marché",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Bull market", "Bear market", "Correction", "Consolidation", "Cycle de Kitchin"],
        practical_example: "2020 : crash COVID (-35% en 33 jours). 2020-2021 : bull market record (+100%). 2022 : bear market (-25%). Reconnaître ces cycles, c'est savoir où on en est.",
      },
      {
        id: 8,
        title: "Quiz final — Marchés financiers",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif global", "Test de compréhension"],
        practical_example: "Évalue tes connaissances acquises dans ce cours.",
      },
    ],
  },

  {
    id: "bases-trading",
    title: "Les bases du trading",
    level: "débutant",
    duration: "1h30",
    chapters_count: 10,
    icon: "📈",
    description: "Apprendre à lire un graphe, passer ses premiers ordres et gérer son capital",
    video_intro: "https://www.youtube.com/embed/dn4R6BGGOCA",
    chapters: [
      {
        id: 1,
        title: "Lire un graphique chandelier (candlestick)",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/dn4R6BGGOCA",
        key_concepts: ["Bougie japonaise", "Corps", "Ombre haute/basse", "Bougie haussière/baissière", "Open/Close/High/Low"],
        practical_example: "Sur le graphique AAPL du 3 janvier 2024 : ouverture $185, clôture $184, high $186, low $183 → bougie rouge avec petites ombres = session indécise légèrement baissière.",
      },
      {
        id: 2,
        title: "Les différents types d'ordres",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Ordre market", "Ordre limite", "Stop-loss", "Stop-limit", "OCO"],
        practical_example: "Tu veux acheter TSLA à $180 max. Tu places un ordre limite à $180. Si le prix descend à $180, l'ordre s'exécute. Si jamais il reste au-dessus, il expire.",
      },
      {
        id: 3,
        title: "Tendances, supports et résistances",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/pdSXxCMBGEI",
        key_concepts: ["Tendance haussière/baissière", "Range", "Support", "Résistance", "Retest"],
        practical_example: "NVDA avait un support solide à $500 en octobre 2023. Chaque fois que le prix touchait ce niveau, des acheteurs intervenaient. Une fois cassé à la hausse, ce support devient résistance.",
      },
      {
        id: 4,
        title: "Les figures chartistes classiques",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Tête-épaules", "Double sommet/creux", "Triangle", "Drapeau", "Biseau"],
        practical_example: "En novembre 2021, Bitcoin a formé un double sommet à $69k. Cette figure a prédit la baisse brutale vers $16k en 2022 — les figures chartistes ont une valeur prédictive réelle.",
      },
      {
        id: 5,
        title: "Les volumes de trading",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Volume", "Volume relatif", "Confirmation de tendance", "Divergence volume/prix"],
        practical_example: "NVIDIA mars 2024 : quand l'action cassait ses plus hauts avec des volumes 3x supérieurs à la normale, c'était un signal de continuation fort — le breakout était confirmé.",
      },
      {
        id: 6,
        title: "Timeframes : du scalping au long terme",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/lUhzT_4QLKU",
        key_concepts: ["Scalping (M1-M5)", "Day trading (M15-H1)", "Swing trading (H4-Daily)", "Position trading (Weekly)"],
        practical_example: "Un scalper sur EUR/USD peut faire 20 trades par jour sur des bougies de 1 minute. Un swing trader sur SPY peut tenir sa position 2 semaines sur un graphique journalier.",
      },
      {
        id: 7,
        title: "Spreads, commissions et slippage",
        duration: "6 min",
        type: "lecture",
        key_concepts: ["Bid/Ask spread", "Commission broker", "Slippage", "Coût total du trade"],
        practical_example: "Avec un spread de 0.5% par trade, 100 trades = 50% de frais. Un broker avec 0% de commission mais spreads larges peut coûter plus cher qu'un broker avec commission fixe.",
      },
      {
        id: 8,
        title: "Choisir son broker",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Régulation", "Effet de levier", "Instruments disponibles", "Plateforme trading", "Dépôt minimum"],
        practical_example: "Interactive Brokers : frais très bas, accès mondial. eToro : copytrading, interface simple. Trade Republic : zéro commission mais uniquement passif. Chaque profil a son broker.",
      },
      {
        id: 9,
        title: "Construire son plan de trading",
        duration: "9 min",
        type: "interactive",
        key_concepts: ["Setup de trading", "Critères d'entrée", "Règles de sortie", "Journal de trading"],
        practical_example: "Plan type : Je trade uniquement le breakout du high de la veille sur des actions S&P 500 > $10B cap. Je risque max 1% par trade avec un R/R minimum de 2:1. Je tradeen pre-market et les 2h suivant l'ouverture.",
      },
      {
        id: 10,
        title: "Quiz final — Bases du trading",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif", "Test final"],
        practical_example: "Évalue ta maîtrise des bases du trading.",
      },
    ],
  },

  {
    id: "psychologie-trader",
    title: "Psychologie du trader",
    level: "débutant",
    duration: "45 min",
    chapters_count: 6,
    icon: "🧠",
    description: "Maîtriser ses émotions, éviter les biais cognitifs et trader avec discipline",
    video_intro: "https://www.youtube.com/embed/fBgBILqJ95s",
    chapters: [
      {
        id: 1,
        title: "Les émotions qui détruisent les traders",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/fBgBILqJ95s",
        key_concepts: ["FOMO", "Panique", "Euphorie", "Revenge trading", "Cycle émotionnel"],
        practical_example: "Janvier 2021 — GameStop. Des milliers de traders ont acheté à $400 par FOMO, incapables de vendre. Le titre est retombé à $40 en quelques semaines. Le FOMO coûte très cher.",
      },
      {
        id: 2,
        title: "Les biais cognitifs en trading",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Biais de confirmation", "Biais d'ancrage", "Effet de dotation", "Aversion à la perte", "Overconfidence"],
        practical_example: "Biais d'ancrage : un trader qui a acheté Tesla à $400 refuse de vendre à $200 car 'ça va remonter à mon prix d'achat'. Il ancre sa référence sur son prix d'entrée, pas sur la réalité.",
      },
      {
        id: 3,
        title: "Discipline et respect des règles",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Checklist pre-trade", "Journal de trading", "Règle des 3 strikes", "Trading mécanique"],
        practical_example: "Paul Tudor Jones, milliardaire du trading, tient un journal depuis 40 ans. Chaque trade documenté : pourquoi j'entre, pourquoi je sors, qu'est-ce que j'apprends. La discipline se construit.",
      },
      {
        id: 4,
        title: "Gérer les pertes et les drawdowns",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/RQYF7FiE4ck",
        key_concepts: ["Drawdown", "Recovery factor", "Losing streak", "Règle du 6%", "Pause obligatoire"],
        practical_example: "Règle : si tu perds 6% du capital dans le mois, tu arrêtes de trader jusqu'au mois suivant. Cette règle a sauvé des milliers de comptes de la destruction totale.",
      },
      {
        id: 5,
        title: "Le mindset du trader professionnel",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Process vs résultats", "Probabilités", "Edge statistique", "Détachement émotionnel"],
        practical_example: "Un pro ne pense pas : 'je vais gagner sur ce trade'. Il pense : 'cette stratégie gagne 60% du temps avec R/R 2:1. Sur 100 trades, je suis profitable. Ce trade individuel ne compte pas.'",
      },
      {
        id: 6,
        title: "Quiz — Psychologie du trader",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif", "Test psychologie"],
        practical_example: "Teste ta compréhension des biais et émotions en trading.",
      },
    ],
  },

  {
    id: "gestion-risque",
    title: "Gestion du risque & Money Management",
    level: "débutant",
    duration: "1h",
    chapters_count: 7,
    icon: "🛡️",
    description: "Protéger son capital, calculer ses positions et survivre aux marchés baissiers",
    video_intro: "https://www.youtube.com/embed/0bKXKLcYHJQ",
    chapters: [
      {
        id: 1,
        title: "Pourquoi la gestion du risque prime sur tout",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/0bKXKLcYHJQ",
        key_concepts: ["Capital preservation", "Asymétrie rendement/risque", "Survie long terme", "Ruin probability"],
        practical_example: "Perte de 50% → il faut +100% pour revenir au départ. Perte de 20% → seulement +25%. Éviter les grosses pertes est mathématiquement plus important que chercher les gros gains.",
      },
      {
        id: 2,
        title: "La règle du 1% et 2%",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Risque par trade", "Taille de position", "Stop-loss distance", "Unités de risque"],
        practical_example: "Capital $10 000. Règle 1% → max $100 risqués par trade. Si ton stop est à 5% de distance, tu peux acheter pour $2 000 d'actions (100 / 0.05 = 2000). Calcul simple, résultats énormes.",
      },
      {
        id: 3,
        title: "Le ratio risque/récompense (R/R)",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Ratio R/R", "Breakeven winrate", "Espérance mathématique", "Target TP vs SL"],
        practical_example: "R/R 1:2 → tu risques $100 pour gagner $200. Avec 40% de trades gagnants : (0.4 × 200) - (0.6 × 100) = +80 - 60 = +$20 d'espérance positive. Profitable même en gagnant moins de la moitié !",
      },
      {
        id: 4,
        title: "La diversification du portefeuille",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/ViMc1hN7_aY",
        key_concepts: ["Corrélation", "Diversification sectorielle", "Nombre optimal de positions", "Concentration vs diversification"],
        practical_example: "Détenir uniquement des tech US en 2022, c'était -40%. Mix : 30% tech + 20% énergie + 20% santé + 30% bonds → -12%. La corrélation faible entre secteurs protège le capital.",
      },
      {
        id: 5,
        title: "La gestion des positions ouvertes",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Trailing stop", "Scale in/out", "Break-even stop", "Pyramidage"],
        practical_example: "Tu achètes AAPL à $170 avec stop à $165. L'action monte à $180. Tu montes ton stop à $170 (break-even). Si ça continue : trailing stop à -3% du plus haut. Tu ne peux plus perdre.",
      },
      {
        id: 6,
        title: "Survivre aux marchés baissiers",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Hedge", "Cash position", "Short selling", "Inverse ETFs", "Réduction d'exposition"],
        practical_example: "Bear market 2022 : les traders qui ont réduit à 30% d'exposition en janvier (breakage de la MA200) ont protégé leur capital. Ceux qui sont restés full invested ont perdu 25-40%.",
      },
      {
        id: 7,
        title: "Quiz — Gestion du risque",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif risk management"],
        practical_example: "Teste tes calculs de taille de position et R/R.",
      },
    ],
  },

  {
    id: "comprendre-crypto",
    title: "Comprendre les cryptomonnaies",
    level: "débutant",
    duration: "1h15",
    chapters_count: 8,
    icon: "₿",
    description: "Bitcoin, Ethereum, blockchain et comment investir dans les crypto en sécurité",
    video_intro: "https://www.youtube.com/embed/SSo_EIwHSd4",
    chapters: [
      {
        id: 1,
        title: "Qu'est-ce que Bitcoin et la blockchain ?",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/SSo_EIwHSd4",
        key_concepts: ["Blockchain", "Décentralisation", "Proof of Work", "Satoshi Nakamoto", "Halving"],
        practical_example: "Le halving Bitcoin d'avril 2024 a réduit la récompense des mineurs de 6.25 à 3.125 BTC. Historiquement, chaque halving précède un bull market de 12-18 mois.",
      },
      {
        id: 2,
        title: "Ethereum et les smart contracts",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Smart contract", "EVM", "Gas fees", "Proof of Stake", "dApps"],
        practical_example: "Un smart contract sur Ethereum peut automatiquement payer un loyer le 1er de chaque mois sans banque. 50 000 dApps tournent sur Ethereum, traitant des milliards de dollars par jour.",
      },
      {
        id: 3,
        title: "Les altcoins : opportunités et risques",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Altcoin", "Market cap", "Tokenomics", "Rug pull", "Due diligence"],
        practical_example: "LUNA en 2022 : top 10 crypto, $40B de market cap → $0 en 72h. Comprendre la tokenomics (comment les tokens sont créés et détruits) est vital avant tout investissement.",
      },
      {
        id: 4,
        title: "Les exchanges et wallets",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/d8IBpfs9bf4",
        key_concepts: ["Exchange centralisé (CEX)", "Exchange décentralisé (DEX)", "Hot wallet", "Cold wallet", "Seed phrase"],
        practical_example: "FTX (exchange centralisé) : $32B de valorisation en 2021 → faillite et perte totale des fonds clients en 2022. Règle : 'Not your keys, not your coins'. Garde tes crypto sur hardware wallet.",
      },
      {
        id: 5,
        title: "Comment acheter ses premières crypto",
        duration: "8 min",
        type: "interactive",
        key_concepts: ["KYC", "DCA (Dollar Cost Averaging)", "Ordre limite", "Stablecoin", "Frais d'achat"],
        practical_example: "DCA sur Bitcoin : investir $100/semaine quelle que soit le prix. Sur 2 ans en 2020-2022, cette stratégie simple a généré +180% même en achetant au plus haut.",
      },
      {
        id: 6,
        title: "Sécuriser ses investissements crypto",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["2FA", "Hardware wallet", "Phishing", "Scams courants", "Backup seed phrase"],
        practical_example: "En 2023, $3.8 milliards de crypto volés. 90% des vols sont évitables : hardware wallet (Ledger/Trezor) + 2FA sur exchanges + jamais partager sa seed phrase.",
      },
      {
        id: 7,
        title: "Fiscalité des crypto en France",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["Plus-value crypto", "Flat tax 30%", "Déclaration 2086", "Swap crypto-to-crypto", "Holding vs trading"],
        practical_example: "En France : toute plus-value crypto est taxée à 30% (flat tax) seulement à la conversion en euros. Swap BTC → ETH sans passer par euros : taxable depuis 2023. Tenir un registre de tous ses trades.",
      },
      {
        id: 8,
        title: "Quiz — Cryptomonnaies",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif crypto"],
        practical_example: "Teste ta compréhension de l'écosystème crypto.",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // INTERMÉDIAIRE (5 cours)
  // ══════════════════════════════════════════════════════════════════

  {
    id: "analyse-technique",
    title: "Analyse technique complète",
    level: "intermédiaire",
    duration: "2h30",
    chapters_count: 12,
    icon: "📊",
    description: "Maîtriser tous les indicateurs techniques : RSI, MACD, Bollinger, Fibonacci",
    video_intro: "https://www.youtube.com/embed/eynxyoKgpng",
    chapters: [
      {
        id: 1,
        title: "Philosophie de l'analyse technique",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/eynxyoKgpng",
        key_concepts: ["Prix intègre tout", "L'histoire se répète", "Tendance vs range", "Dow Theory", "Efficience des marchés"],
        practical_example: "S&P 500 2020 : le marché a anticipé la reprise économique 6 mois avant qu'elle soit visible dans les données macro. Le prix 'savait' avant les économistes.",
      },
      {
        id: 2,
        title: "RSI — Relative Strength Index",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["RSI(14)", "Zones surachat/survente", "Divergence RSI/prix", "RSI sur différents timeframes"],
        practical_example: "Bitcoin avril 2021 : RSI(14) à 89 (extrême surachat) sur le graphique hebdomadaire = signal de correction majeure. 3 semaines plus tard : -50%. La divergence baissière du RSI précède souvent les tops.",
      },
      {
        id: 3,
        title: "MACD — Moving Average Convergence Divergence",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["MACD Line", "Signal Line", "Histogramme", "Croisement", "Divergence MACD"],
        practical_example: "Tesla Q4 2023 : histogramme MACD passait positif pour la première fois en 2 mois, avec le MACD croisant au-dessus du signal. L'action a rallié +40% dans les 6 semaines suivantes.",
      },
      {
        id: 4,
        title: "Bandes de Bollinger",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/tkwUOUZQSkE",
        key_concepts: ["Bande haute/basse/médiane", "Squeeze Bollinger", "Breakout des bandes", "BB Width", "%B indicator"],
        practical_example: "Amazon avant ses résultats Q3 2023 : squeeze Bollinger extrême (bandes très resserrées) pendant 2 semaines. La compression précède toujours l'expansion. Résultats publiés → breakout +8% en une nuit.",
      },
      {
        id: 5,
        title: "Moyennes mobiles : EMA, SMA, VWAP",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["SMA vs EMA", "MA50, MA200", "Golden cross / Death cross", "VWAP intraday", "MA comme support/résistance"],
        practical_example: "Golden cross sur SPY en janvier 2023 (MA50 croise MA200 à la hausse) → début du bull market 2023. Ce signal a précédé une hausse de +25% dans l'année.",
      },
      {
        id: 6,
        title: "Fibonacci — Retracements et extensions",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/MvBWYJcnLuA",
        key_concepts: ["Niveaux Fibonacci (23.6%, 38.2%, 61.8%)", "Retracement vs extension", "Zone dorée", "Confluence Fibonacci"],
        practical_example: "AAPL octobre 2023 : après un rally de $165 à $198, le prix a retracé exactement à 61.8% de Fibonacci ($178) avant de repartir vers de nouveaux sommets. La zone dorée tient souvent.",
      },
      {
        id: 7,
        title: "Stochastique, Williams %R, CCI",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Stochastique K/D", "Williams %R", "CCI", "Oscillateurs de momentum", "Confluence oscillateurs"],
        practical_example: "Quand RSI < 30 ET Williams %R < -80 ET Stoch < 20 simultanément sur NVDA, c'est une confluence rare. Ces trois surventes simultanées précèdent souvent des rebonds puissants.",
      },
      {
        id: 8,
        title: "ATR — Average True Range et volatilité",
        duration: "7 min",
        type: "lecture",
        key_concepts: ["ATR", "Mesure de volatilité", "Position sizing par ATR", "Stop ATR-based"],
        practical_example: "Si l'ATR(14) d'une action est $5, placer un stop à $2 du prix est trop serré — tu seras stopped par le bruit normal du marché. Un stop à 2× ATR = $10 est plus adapté.",
      },
      {
        id: 9,
        title: "OBV et indicateurs de volume",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["On-Balance Volume", "Volume Profile", "Accumulation/Distribution", "Volume MA"],
        practical_example: "Nvidia début 2023 : l'OBV montait régulièrement pendant que le prix consolidait. Cette divergence bullish a précédé le mega-rally de +200% sur l'année.",
      },
      {
        id: 10,
        title: "Confluence et stratégies multi-indicateurs",
        duration: "10 min",
        type: "interactive",
        key_concepts: ["Confluence", "Filtre de signal", "Score technique", "Éviter les faux signaux"],
        practical_example: "Notre système FinanceApp utilise 17 indicateurs pondérés. Un signal avec 80% de confluence = 5 indicateurs fort alignés. Cette approche filtre 70% des faux signaux par rapport à un seul indicateur.",
      },
      {
        id: 11,
        title: "Backtesting de stratégies techniques",
        duration: "9 min",
        type: "interactive",
        key_concepts: ["Backtesting", "Overfitting", "In-sample vs out-of-sample", "Métriques de performance"],
        practical_example: "Notre outil Backtest (onglet Analyses) te permet de tester RSI Reversal sur AAPL en 2023. Résultat : 67% win rate, +23% rendement, max drawdown 8%. Valide la stratégie avant de trader en réel.",
      },
      {
        id: 12,
        title: "Quiz final — Analyse technique",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif analyse technique"],
        practical_example: "Test complet sur tous les indicateurs techniques.",
      },
    ],
  },

  {
    id: "analyse-fondamentale",
    title: "Analyse fondamentale",
    level: "intermédiaire",
    duration: "2h",
    chapters_count: 10,
    icon: "🔍",
    description: "Évaluer une entreprise, lire les bilans financiers et trouver des actions sous-évaluées",
    video_intro: "https://www.youtube.com/embed/ZY6zXn0WQLE",
    chapters: [
      {
        id: 1,
        title: "Pourquoi l'analyse fondamentale ?",
        duration: "8 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/ZY6zXn0WQLE",
        key_concepts: ["Valeur intrinsèque", "Warren Buffett", "Investissement valeur", "Marge de sécurité", "Long terme"],
        practical_example: "Buffett achète Apple en 2016 à $27 ajusté (splits). En 2024, Apple vaut $185. Raison : business exceptionnel, moat, cashflow. La fondamentale sur 8 ans = +585%.",
      },
      {
        id: 2,
        title: "Lire un bilan comptable",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Actif", "Passif", "Capitaux propres", "Dette nette", "Goodwill"],
        practical_example: "Apple Q3 2024 : $162B de cash, $104B de dette → dette nette négative. L'entreprise a plus de cash que de dette. C'est une forteresse financière — risque de faillite quasi nul.",
      },
      {
        id: 3,
        title: "Compte de résultat et marges",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Chiffre d'affaires", "Marge brute", "EBITDA", "Marge nette", "EPS (Earnings Per Share)"],
        practical_example: "NVIDIA FY2024 : CA $61B (+122% YoY), marge nette 55%. Pour chaque dollar de revenus, NVIDIA en garde 55 cents. C'est une des marges les plus élevées de toute l'histoire des entreprises tech.",
      },
      {
        id: 4,
        title: "Les ratios de valorisation",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/AoHjIbF3BuA",
        key_concepts: ["P/E ratio", "PEG ratio", "P/B ratio", "EV/EBITDA", "Price/Sales"],
        practical_example: "Meta en novembre 2022 : P/E de 8x, considéré comme très bon marché. Buffett-like : le marché paniquait, les fondamentaux étaient solides. 1 an plus tard : +200%. Les ratios bas = opportunités.",
      },
      {
        id: 5,
        title: "Cashflow libre et valorisation DCF",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Free Cash Flow", "DCF (Discounted Cash Flow)", "WACC", "Terminal Value", "Valeur intrinsèque"],
        practical_example: "DCF simple sur Apple : FCF actuel $100B/an, croissance 10%/an sur 10 ans, WACC 9%. Valeur intrinsèque calculée : ~$3T. Capitalisation actuelle : $2.8T → légèrement sous-valorisée selon ce modèle.",
      },
      {
        id: 6,
        title: "Le moat concurrentiel",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Economic moat", "Effets réseau", "Coûts de switching", "Marques", "Brevets"],
        practical_example: "Visa : 4 milliards de cartes en circulation, acceptée dans 200 pays. Construire un réseau concurrent prendrait 50 ans et des centaines de milliards. C'est le moat ultime — Buffett en est actionnaire depuis 2011.",
      },
      {
        id: 7,
        title: "Analyse sectorielle et macro",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Cyclique vs défensif", "TAM (Total Addressable Market)", "Position concurrentielle", "Cycle sectoriel"],
        practical_example: "Secteur semiconducteur 2024 : la demande IA crée un TAM de +$500B d'ici 2030. Les semiconducteurs sont cycliques mais l'IA est un mégatrend séculaire. NVDA + AMD + AVGO sont les bénéficiaires directs.",
      },
      {
        id: 8,
        title: "Les catalyseurs de croissance",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Earnings surprises", "Guidance", "Expansion internationale", "M&A", "Nouveaux produits"],
        practical_example: "Apple Vision Pro annoncé juin 2023 → l'action +4% en une journée malgré des ventes limitées. Le marché valorise les futurs revenus potentiels d'une nouvelle catégorie produit.",
      },
      {
        id: 9,
        title: "Construire sa thèse d'investissement",
        duration: "9 min",
        type: "interactive",
        key_concepts: ["Thèse haussière", "Risques identifiés", "Prix cible", "Horizon d'investissement", "Stop fondamental"],
        practical_example: "Thèse META 2022 : 'Le marché punit excessivement Zuckerberg pour le Metaverse. Le core business (publicité) génère $40B FCF/an. Objectif 18 mois : $250 → résultat réel : $350.'",
      },
      {
        id: 10,
        title: "Quiz — Analyse fondamentale",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif fondamentale"],
        practical_example: "Teste ta capacité à évaluer une entreprise.",
      },
    ],
  },

  {
    id: "trading-actions",
    title: "Trading d'actions US",
    level: "intermédiaire",
    duration: "1h45",
    chapters_count: 9,
    icon: "🇺🇸",
    description: "NYSE, NASDAQ, S&P500 — trader les actions américaines comme un pro",
    video_intro: "https://www.youtube.com/embed/Xn7KWR9EOGQ",
    chapters: [
      {
        id: 1,
        title: "L'écosystème des marchés US",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/Xn7KWR9EOGQ",
        key_concepts: ["NYSE vs NASDAQ", "S&P 500", "Russell 2000", "Pre-market / After-hours", "Circuit breakers"],
        practical_example: "Le Nasdaq a chuté de -13% en un jour en mars 2020 (COVID). Les circuit breakers ont arrêté le trading 3 fois. Ces protections évitent les paniques totales.",
      },
      {
        id: 2,
        title: "Les earnings — résultats trimestriels",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["EPS attendu vs réalisé", "Guidance", "Beat/miss", "Volatilité earnings", "Options earnings play"],
        practical_example: "Meta Q3 2023 : EPS attendu $3.63, réalisé $4.39 (+21% au-dessus). L'action a gagné +20% en une nuit. Shorter Meta avant cet earnings aurait détruit le compte.",
      },
      {
        id: 3,
        title: "Sectors Rotation — la rotation sectorielle",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Rotation sectorielle", "Risk-on vs Risk-off", "Taux d'intérêt et valorisations", "Momentum sectoriel"],
        practical_example: "2022 : hausse des taux Fed → rotation hors de la tech (taux bas nécessaires aux valorisations élevées) vers l'énergie (+60%) et la finance (+10%). Comprendre la rotation = surperformer.",
      },
      {
        id: 4,
        title: "Les stratégies de momentum",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/aYtLl9WDR7o",
        key_concepts: ["Price momentum", "Relative strength", "Breakout trading", "52-week high strategy"],
        practical_example: "NVDA juin 2023 : breakout au-dessus du plus haut de 52 semaines à $400 avec volumes 5x la normale. Signal de momentum fort. L'action a continué jusqu'à $900 en 6 mois.",
      },
      {
        id: 5,
        title: "Gap trading et catalyseurs",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Gap up/down", "Gap fill", "Earnings gap", "News gap", "Gap and go vs fade"],
        practical_example: "Apple post-earnings Q2 2023 : gap up de +5% à l'ouverture. Les stats montrent que 70% des gaps earnings > 5% ne se comblent pas le même jour. Stratégie : aller dans la direction du gap.",
      },
      {
        id: 6,
        title: "Short selling — vendre à découvert",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Short selling", "Short squeeze", "Borrow rate", "Days to cover", "Short interest"],
        practical_example: "GameStop janvier 2021 : 140% du float vendu à découvert. Quand les Reddit traders ont acheté massivement, les shorts ont dû couvrir → short squeeze de +1700% en 2 semaines. Morale : surveiller le short interest.",
      },
      {
        id: 7,
        title: "L'analyse des options comme signal",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Open interest", "Put/Call ratio", "Options flow", "Dark pool", "Unusual activity"],
        practical_example: "Outil 'unusual options activity' : en octobre 2023, des calls massifs sur AMD ont été repérés à $120 (prix à $100). 6 semaines plus tard, AMD était à $125. Les options smart money précèdent les mouvements.",
      },
      {
        id: 8,
        title: "Construire un watchlist et un screener",
        duration: "9 min",
        type: "interactive",
        key_concepts: ["Screener technique", "Critères de sélection", "Watchlist organisation", "Alertes prix"],
        practical_example: "Screener setup : actions US > $5B cap, RSI(14) entre 40-60, volume > 1.5x la moyenne, au-dessus de la MA50. Ce filtre identifie des setups de continuation propres sans surachat ni survente.",
      },
      {
        id: 9,
        title: "Quiz — Trading actions US",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif marchés US"],
        practical_example: "Teste ta compréhension des marchés américains.",
      },
    ],
  },

  {
    id: "defi-web3",
    title: "DeFi & Web3",
    level: "intermédiaire",
    duration: "1h30",
    chapters_count: 8,
    icon: "⛓️",
    description: "Uniswap, yield farming, NFTs et les protocoles DeFi les plus importants",
    video_intro: "https://www.youtube.com/embed/k9HYC0EJU6E",
    chapters: [
      {
        id: 1,
        title: "Comprendre la finance décentralisée (DeFi)",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/k9HYC0EJU6E",
        key_concepts: ["DeFi vs CeFi", "TVL (Total Value Locked)", "Permissionless", "Composabilité", "Smart contracts"],
        practical_example: "DeFi en 2021 : $180B de TVL. Aave permet d'emprunter de l'ETH en déposant du Bitcoin comme collateral — sans banque, sans KYC, en 2 minutes. Un service bancaire révolutionnaire.",
      },
      {
        id: 2,
        title: "AMM et Uniswap — les DEX",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["AMM", "Liquidity pool", "Impermanent loss", "Slippage", "LP tokens"],
        practical_example: "Uniswap traite $1B+ de volume par jour sans carnet d'ordres. La formule x×y=k détermine automatiquement les prix. Un pool ETH/USDC avec $10M de liquidité = faible slippage pour les traders.",
      },
      {
        id: 3,
        title: "Yield Farming et Staking",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Yield farming", "APY vs APR", "Liquidité mining", "Staking", "Risques de protocole"],
        practical_example: "Fournir de la liquidité sur Uniswap ETH/USDC : frais de 0.3% sur chaque swap. Si le pool traite $100M/jour, les LPs reçoivent $300K/jour. APY réel (en incluant l'impermanent loss) : calcul complexe.",
      },
      {
        id: 4,
        title: "Lending et Borrowing — Aave et Compound",
        duration: "9 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/WwE3lUq51gQ",
        key_concepts: ["Overcollateralisation", "Liquidation", "Health factor", "Flash loans", "Taux variables"],
        practical_example: "Aave 2024 : dépose 1 ETH ($3000) comme collateral → emprunte $1500 USDC (50% LTV). Si ETH chute et ton health factor < 1, tu es liquidé. Flash loans : emprunter $1M sans collateral, tout rembourser en 1 transaction.",
      },
      {
        id: 5,
        title: "Les NFTs et les marchés d'actifs numériques",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["NFT", "Token ERC-721", "OpenSea", "Royalties", "Utilité vs spéculation"],
        practical_example: "BAYC (Bored Ape Yacht Club) peak 2022 : floor price 150 ETH ($430k). En 2024 : 12 ETH ($42k). Les NFTs purement spéculatifs sans utilité ont perdu 90%. Les NFTs avec utilité réelle (gaming, ticketing) survivent mieux.",
      },
      {
        id: 6,
        title: "Layer 2 — Ethereum scaling",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Rollup", "Arbitrum", "Optimism", "zkSync", "Bridging"],
        practical_example: "Arbitrum réduit les frais Ethereum de $50 à $0.10 par transaction en regroupant des milliers de txs en une. En 2024, Arbitrum traite plus de transactions qu'Ethereum mainnet.",
      },
      {
        id: 7,
        title: "Les risques du DeFi",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Smart contract bug", "Oracle manipulation", "Rug pull", "Bridge hack", "Réglementation"],
        practical_example: "Ronin Bridge hack mars 2022 : $625M volés. Un hacker a compromis 5 des 9 validateurs du réseau et transféré les fonds. Les bridges cross-chain sont les cibles les plus vulnérables du DeFi.",
      },
      {
        id: 8,
        title: "Quiz — DeFi & Web3",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif DeFi"],
        practical_example: "Teste ta compréhension des protocoles DeFi.",
      },
    ],
  },

  {
    id: "options-derives",
    title: "Options & Produits dérivés",
    level: "intermédiaire",
    duration: "2h",
    chapters_count: 10,
    icon: "⚙️",
    description: "Calls, puts, Greeks, stratégies d'options pour amplifier ses gains",
    video_intro: "https://www.youtube.com/embed/7PM4rNDr4oI",
    chapters: [
      {
        id: 1,
        title: "Qu'est-ce qu'une option ?",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/7PM4rNDr4oI",
        key_concepts: ["Call", "Put", "Strike price", "Date d'expiration", "Prime d'option"],
        practical_example: "Tu achètes un call AAPL $190 exp. 30 jours pour $3 (prime). Si AAPL monte à $200, ton option vaut $10 (+233%). Si AAPL reste à $185, l'option expire sans valeur : tu perds $3.",
      },
      {
        id: 2,
        title: "Valeur intrinsèque et valeur temps",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["In-the-money (ITM)", "At-the-money (ATM)", "Out-of-the-money (OTM)", "Time decay", "Valeur temps"],
        practical_example: "Option ATM à 30 jours : 50% prime = valeur temps. À 7 jours : 80% de time decay déjà passé. Les vendeurs d'options aiment l'approche de l'expiration — le temps est leur allié.",
      },
      {
        id: 3,
        title: "Les Greeks : Delta, Gamma, Theta, Vega",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Delta (Δ)", "Gamma (Γ)", "Theta (Θ)", "Vega (ν)", "Rho"],
        practical_example: "Option NVDA delta 0.5 : si NVDA monte de $1, ton option prend $0.50. Theta -0.05 : tu perds $0.05/jour juste avec le passage du temps. Vega 0.15 : si la volatilité implicite monte de 1%, l'option prend $0.15.",
      },
      {
        id: 4,
        title: "Les stratégies de base",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/7a-Ap5vSFRE",
        key_concepts: ["Long call", "Long put", "Covered call", "Protective put", "Cash-secured put"],
        practical_example: "Covered call sur AAPL : tu détiens 100 actions à $180. Tu vends un call $190 exp. 30 jours pour $3 de prime. Résultat : si AAPL reste sous $190, tu empêches $300 de revenus supplémentaires chaque mois.",
      },
      {
        id: 5,
        title: "Spreads : Bull call, Bear put, Iron Condor",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Bull call spread", "Bear put spread", "Iron condor", "Butterfly", "Max loss défini"],
        practical_example: "Iron condor sur SPY : vente call $500 + achat call $510 + vente put $430 + achat put $420. Tu encaisses $2 de prime. Tant que SPY reste entre $430 et $500, tu gardes tout. Stratégie idéale en faible volatilité.",
      },
      {
        id: 6,
        title: "La volatilité implicite (IV)",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["IV vs volatilité historique", "IV crush post-earnings", "VIX", "Percentile IV", "IV rank"],
        practical_example: "Avant earnings NVDA : IV 80%. Après publication (même positifs) : IV 45%. L'option a perdu 40% malgré la hausse de l'action — c'est le 'IV crush'. Vendre de la IV avant earnings peut être profitable.",
      },
      {
        id: 7,
        title: "Stratégies sur dividendes et événements",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Ex-dividend date", "Options et dividendes", "Earnings play", "M&A options"],
        practical_example: "Apple verse $0.24 de dividende trimestriel. Acheter un call ITM juste avant l'ex-date peut être optimisé via les stratégies de 'dividend capture' en combinant stock et options.",
      },
      {
        id: 8,
        title: "Risk management avec les options",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Max loss défini", "Hedge de portefeuille", "Rolling des positions", "Assignment risk"],
        practical_example: "Hedger 100k$ de portefeuille actions US pendant un krach : acheter 2 puts SPY $430 à $500 chacun = $1000. Si SPY chute de 20%, ces puts valent $8000 → +$7000 qui compensent les pertes.",
      },
      {
        id: 9,
        title: "Les options sur indices et ETF",
        duration: "8 min",
        type: "lecture",
        key_concepts: ["Options SPX vs SPY", "Cash settlement", "Règlement européen vs américain", "Options hebdomadaires"],
        practical_example: "SPX options (cash-settled, pas d'assignment de stock) vs SPY options (assignment possible). Les pros préfèrent SPX pour les grandes stratégies institutionnelles — taille des contrats x10.",
      },
      {
        id: 10,
        title: "Quiz — Options & Dérivés",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif options"],
        practical_example: "Teste ta maîtrise des options et des Greeks.",
      },
    ],
  },

  // ══════════════════════════════════════════════════════════════════
  // AVANCÉ (5 cours)
  // ══════════════════════════════════════════════════════════════════

  {
    id: "trading-algorithmique",
    title: "Trading algorithmique",
    level: "avancé",
    duration: "3h",
    chapters_count: 12,
    icon: "🤖",
    description: "Créer des bots de trading, backtester des stratégies et automatiser ses trades",
    video_intro: "https://www.youtube.com/embed/9Y3yaoi9rUQ",
    chapters: [
      {
        id: 1,
        title: "Introduction au trading algorithmique",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/9Y3yaoi9rUQ",
        key_concepts: ["Quant trading", "HFT vs systematic trading", "Alpha", "Exécution automatisée", "Backtesting"],
        practical_example: "Renaissance Technologies (Medallion Fund) : +66% par an depuis 1988 avec des algorithmes purs. Le secret : traiter les marchés comme un problème de physique statistique.",
      },
      {
        id: 2,
        title: "Collecte et préparation des données",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["OHLCV data", "Données alternatives", "Normalisation", "Survivorship bias", "Look-ahead bias"],
        practical_example: "Yahoo Finance API : données gratuites mais avec survivorship bias (les entreprises faillies disparaissent). Pour un backtest propre, utiliser des données point-in-time incluant les délisted stocks.",
      },
      {
        id: 3,
        title: "Indicateurs techniques en code",
        duration: "12 min",
        type: "interactive",
        key_concepts: ["RSI en Python/TS", "EMA calculation", "Vectorisation", "Pandas/NumPy", "TA-Lib"],
        practical_example: "Notre /app/api/signals/route.ts calcule 14 indicateurs en temps réel sur 100 actifs simultanément. La vectorisation permet de traiter 1 an de données en <50ms.",
      },
      {
        id: 4,
        title: "Concevoir une stratégie algorithmique",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Hypothèse de trading", "Règles d'entrée/sortie", "Univers de trading", "Filtres de signal"],
        practical_example: "Hypothèse : 'Les actions qui cassent leur high de 52 semaines avec un volume 2x la normale continuent dans la direction du breakout 65% du temps sur les 20 séances suivantes.'",
      },
      {
        id: 5,
        title: "Backtesting rigoureux",
        duration: "12 min",
        type: "interactive",
        key_concepts: ["Walk-forward testing", "Cross-validation", "Transaction costs", "Slippage modeling", "Métriques Sharpe, Calmar"],
        practical_example: "Notre outil Backtest (section Analyses) simule les 5 stratégies principales. Un Sharpe > 1 en backtest = stratégie candidate. Mais l'overfitting est le piège : trop optimiser = mauvaises performances réelles.",
      },
      {
        id: 6,
        title: "Optimisation et paramétrage",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Grid search", "Overfitting", "Régularisation", "Robustesse des paramètres", "Monte Carlo"],
        practical_example: "RSI sur AAPL : periode=14 → Sharpe 1.2. Période=7 → Sharpe 1.8 en backtest. Mais sur données out-of-sample : période=7 → Sharpe 0.3. L'overfitting est dévastateur en trading réel.",
      },
      {
        id: 7,
        title: "Exécution des ordres et API broker",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["API broker", "WebSocket", "Latence", "Slippage réel", "Order management system"],
        practical_example: "Interactive Brokers API (ibkr) : connexion WebSocket pour données temps réel < 5ms de latence. Alpaca API : gratuit, paper trading inclus. Pour commencer en algo : Alpaca + Python est le setup optimal.",
      },
      {
        id: 8,
        title: "Gestion du risque algorithmique",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Position limits", "Drawdown circuit breaker", "Correlation limits", "Stress testing"],
        practical_example: "Règle automatique : si le bot perd >5% en un jour, arrêt automatique et alerte. Si corrélation entre positions dépasse 0.7, réduction automatique. Le bot gère le risque sans intervention humaine.",
      },
      {
        id: 9,
        title: "Mean reversion vs trend following",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Mean reversion", "Trend following", "Stationnarité", "Cointegration", "Pairs trading"],
        practical_example: "Pairs trading : AAPL et MSFT sont coïntégrés (évoluent ensemble). Si le spread s'écarte de 2 écarts-types, acheter le sous-performant et shorter le sur-performant. Retour à la moyenne historique = profit.",
      },
      {
        id: 10,
        title: "Machine Learning pour le trading",
        duration: "12 min",
        type: "lecture",
        key_concepts: ["Features engineering", "Random Forest", "LSTM", "Overfitting ML", "Interprétabilité"],
        practical_example: "LSTM sur Bitcoin : prédire la direction du prix J+1 avec 60 jours d'historique. Accuracy en backtest : 58%. Sur données live : 51%. La différence = overfitting. Le ML en trading est difficile mais prometteur.",
      },
      {
        id: 11,
        title: "Infrastructure et déploiement",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Cloud trading", "Uptime 99.9%", "Monitoring", "Logs", "Alertes"],
        practical_example: "Setup minimal : VPS $20/mois (AWS EC2) + crontab pour exécution horaire + Telegram bot pour alertes. Pour HFT : co-location chez les exchanges ($10k+/mois) pour réduire la latence à <1ms.",
      },
      {
        id: 12,
        title: "Quiz — Trading algorithmique",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif algo trading"],
        practical_example: "Teste ta maîtrise du trading quantitatif.",
      },
    ],
  },

  {
    id: "market-making",
    title: "Market Making & Liquidité",
    level: "avancé",
    duration: "2h",
    chapters_count: 8,
    icon: "💧",
    description: "Comprendre le carnet d'ordres, le market making et les stratégies HFT",
    video_intro: "https://www.youtube.com/embed/Kl4-VJ2K8Ik",
    chapters: [
      {
        id: 1,
        title: "Le carnet d'ordres (order book)",
        duration: "12 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/Kl4-VJ2K8Ik",
        key_concepts: ["Bid/Ask", "Market depth", "Level 2 data", "Order flow", "Tape reading"],
        practical_example: "AAPL à 15h30 : 50 000 actions à l'achat à $182.50, 30 000 actions à la vente à $182.51. Spread = 1 centime. C'est la liquidité des large caps. Sur une small cap, le spread peut être 1-2% du prix.",
      },
      {
        id: 2,
        title: "Qu'est-ce que le market making ?",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Market maker", "Spread capture", "Inventory risk", "Réglementation", "PFOF"],
        practical_example: "Citadel Securities est le plus grand market maker US : traite 25% des ordres retail américains. Revenue model : capturer le spread bid/ask milliards de fois par jour. Citadel paie Robinhood pour router ses ordres.",
      },
      {
        id: 3,
        title: "Microstructure des marchés",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Price impact", "Kyle's lambda", "Adverse selection", "Informed vs uninformed traders", "Fragmentation"],
        practical_example: "Un hedge fund essaie d'acheter 1M d'actions. S'il place un gros ordre d'un coup, le prix monte immédiatement (impact). Technique TWAP/VWAP : fractionner l'ordre sur 4h pour minimiser l'impact.",
      },
      {
        id: 4,
        title: "Trading haute fréquence (HFT)",
        duration: "11 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/cawde0Q7gM0",
        key_concepts: ["Latence", "Co-location", "Flash crash", "Quote stuffing", "Réglementation HFT"],
        practical_example: "Flash crash mai 2010 : le Dow a perdu 1000 points en 10 minutes avant de récupérer. Un algorithme HFT défaillant a amplifié la vente. La SEC a ensuite imposé des circuit breakers obligatoires.",
      },
      {
        id: 5,
        title: "Dark pools et marchés alternatifs",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Dark pool", "ATS", "Block trading", "Avantages des dark pools", "Controverse"],
        practical_example: "40% du volume US se trade en dark pools. Un fonds veut vendre 5M d'actions AAPL sans faire chuter le prix : il utilise un dark pool pour trouver un acheteur institutionnel au même prix sans révéler l'ordre.",
      },
      {
        id: 6,
        title: "Stratégies de market making sur les cryptos",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["AMM vs order book", "Avellaneda-Stoikov", "Inventory management", "Crypto spreads", "DeFi market making"],
        practical_example: "Market making sur Binance BTC/USDT : placer des ordres $0.50 au-dessus et en-dessous du mid. Si le spread est $1, chaque transaction bilatérale capture $0.50. Avec $1M de capital et $100M de volume/jour = $50K/jour brut.",
      },
      {
        id: 7,
        title: "Analyse du flux d'ordres (order flow)",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Delta", "Footprint chart", "Volume at price", "Absorption", "Iceberg orders"],
        practical_example: "Footprint chart sur SPY : une grande absorption d'ordres vendeurs à $450 (beaucoup de sells, mais le prix ne baisse pas) indique un acheteur institutionnel caché. Signal haussier fort.",
      },
      {
        id: 8,
        title: "Quiz — Market Making",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif microstructure"],
        practical_example: "Teste ta compréhension du market making et de la liquidité.",
      },
    ],
  },

  {
    id: "macro-trading",
    title: "Macro Trading & Économie",
    level: "avancé",
    duration: "2h30",
    chapters_count: 10,
    icon: "🌐",
    description: "Taux d'intérêt, inflation, cycles économiques et leur impact sur les marchés",
    video_intro: "https://www.youtube.com/embed/PHe0bXAIuk0",
    chapters: [
      {
        id: 1,
        title: "Les grands cycles économiques",
        duration: "11 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/PHe0bXAIuk0",
        key_concepts: ["Cycle de Kondratieff", "Cycle court Kitchin", "Cycle long Juglar", "Expansion/Récession", "Ray Dalio debt machine"],
        practical_example: "Ray Dalio 2008 : Bridgewater avait modélisé le 'debt supercycle'. Sa thèse prévoyait un crash financier 2 ans avant. Son fonds a gagné +9% pendant que les autres perdaient 40%.",
      },
      {
        id: 2,
        title: "Politique monétaire et banques centrales",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Federal Reserve", "BCE", "QE/QT", "Taux directeurs", "Forward guidance"],
        practical_example: "Fed mars 2022 → mars 2023 : taux de 0% à 5.25% en 12 mois (hausse la plus rapide depuis 40 ans). Impact : NASDAQ -35%, immobilier -20%, dollar +15%. La politique monétaire dicte les marchés.",
      },
      {
        id: 3,
        title: "L'inflation et ses impacts marché",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["CPI", "PCE", "Inflation core vs headline", "Stagflation", "TIPS et protection inflation"],
        practical_example: "2022 : inflation 9.1% aux US. Assets qui ont protégé : pétrole +60%, dollars +15%, TIPS +3%. Assets détruits : obligations -17%, NASDAQ -33%. Comprendre l'inflation = savoir où se réfugier.",
      },
      {
        id: 4,
        title: "Les taux d'intérêt et les marchés",
        duration: "11 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/rvIVFsmhXvI",
        key_concepts: ["Courbe des taux", "Inversion courbe (récession signal)", "Duration", "Spread crédit", "Taux réels vs nominaux"],
        practical_example: "Courbe 10-2 ans inversée depuis juillet 2022 : historiquement, récession dans les 12-18 mois. La Fed a réussi un 'soft landing' rare en 2024 — mais l'inversion avait bien prédit le ralentissement.",
      },
      {
        id: 5,
        title: "Forex — le marché des devises",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Paire de devises", "Dollar index (DXY)", "Carry trade", "Parité de pouvoir d'achat", "Intervention banque centrale"],
        practical_example: "Carry trade classique : emprunter en JPY (taux 0.1%) pour investir en USD (taux 5.5%) = spread de 5.4%/an. Rentable tant que le yen ne s'apprécie pas. Août 2024 : dénouement brutal du carry trade → crash mondial.",
      },
      {
        id: 6,
        title: "Les matières premières comme indicateurs",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Or comme refuge", "Pétrole et inflation", "Cuivre et croissance", "Soft commodities", "Supercycle matières premières"],
        practical_example: "Cuivre = 'Dr Copper' : prédicteur de la croissance mondiale. Si le cuivre monte, l'industrie tourne bien. En 2020, le cuivre a anticipé la reprise 6 mois avant les statistiques officielles.",
      },
      {
        id: 7,
        title: "Risk-on vs Risk-off — allocation globale",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Risk-on assets", "Risk-off assets", "Flight to quality", "Corrélation inter-marchés", "Regime detection"],
        practical_example: "Risk-off : VIX monte, or monte, JPY monte, Treasuries montent, Bitcoin et actions baissent. Si ces 5 signaux s'alignent → réduire l'exposition aux actifs risqués est une décision rationnelle.",
      },
      {
        id: 8,
        title: "Les grandes thèses macro actuelles",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Dédollarisation", "Réindustrialisation", "Transition énergétique", "IA et productivité", "Vieillissement démographique"],
        practical_example: "Thèse réindustrialisation US (CHIPS Act, IRA) : $2T d'investissements industriels en 10 ans. Bénéficiaires : ETF AIRR, aciers américains, semiconducteurs. Un macro trader positionné en 2022 sur ce thème est up +120%.",
      },
      {
        id: 9,
        title: "Construire un portefeuille macro",
        duration: "10 min",
        type: "interactive",
        key_concepts: ["All-weather portfolio", "Risk parity", "Factor exposure", "Rebalancing", "Barbell strategy"],
        practical_example: "Portefeuille All Weather de Dalio : 30% actions, 40% obligations LT, 15% obligations MT, 7.5% or, 7.5% matières premières. Drawdown max historique : -11% (vs -50% pour 100% actions en 2008).",
      },
      {
        id: 10,
        title: "Quiz — Macro Trading",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif macro"],
        practical_example: "Teste ta compréhension de l'économie et des marchés.",
      },
    ],
  },

  {
    id: "hedge-fund-strategies",
    title: "Stratégies de Hedge Funds",
    level: "avancé",
    duration: "2h",
    chapters_count: 9,
    icon: "🏦",
    description: "Long/short equity, arbitrage, global macro — les stratégies des meilleurs fonds",
    video_intro: "https://www.youtube.com/embed/cawde0Q7gM0",
    chapters: [
      {
        id: 1,
        title: "L'univers des hedge funds",
        duration: "10 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/cawde0Q7gM0",
        key_concepts: ["Structure hedge fund", "2 et 20", "AUM", "Leverage", "Lock-up period"],
        practical_example: "Bridgewater ($150B AUM) : frais 1.5% + 15% de performance. Sur $150B et +15% de retour → $22.5B de frais performance en 1 an. Les HF sont les structures financières les plus lucratives au monde.",
      },
      {
        id: 2,
        title: "Long/Short Equity",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Long/short", "Net exposure", "Gross exposure", "Sector neutral", "130/30 strategy"],
        practical_example: "Ackman 2011 : long AAPL, short Herbalife. Position short HLF maintenue 5 ans, perte de $1B. Long AAPL : +300%. La stratégie L/S peut générer alpha des deux côtés — mais le short coûte cher en temps.",
      },
      {
        id: 3,
        title: "Arbitrage statistique (Stat Arb)",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Cointegration", "Mean reversion", "Z-score", "Signal-to-noise", "Pairs trading"],
        practical_example: "Visa et Mastercard : coïntégrés depuis 20 ans. Si le spread Z-score dépasse 2.5 (rare, <5% du temps), vente du sur-performant et achat du sous-performant. Return moyen : 8-12%/an avec faible corrélation au marché.",
      },
      {
        id: 4,
        title: "Global Macro",
        duration: "11 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/nu4S5MdQ7hk",
        key_concepts: ["Soros réflexivité", "Carry trade", "Momentum macro", "Thèmes séculaires"],
        practical_example: "Soros 1992 : conviction que la livre sterling était surévaluée dans le SME. Short £10B. La livre dévalue, il gagne $1B en une nuit. C'est la trade la plus célèbre de l'histoire — basée sur la macro pure.",
      },
      {
        id: 5,
        title: "Event Driven — fusions et acquisitions",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Merger arbitrage", "Risk arbitrage", "Deal spread", "Break risk", "Special situations"],
        practical_example: "Microsoft achète Activision à $95/action. L'action trade à $90 (deal spread 5.5%) pendant 18 mois d'incertitude réglementaire. Les merger arb funds encaissent ce spread si le deal se finalise.",
      },
      {
        id: 6,
        title: "Distressed Debt & Credit",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Obligations distressed", "Restructuration", "Credit default swap", "Recovery rate", "Distressed investing"],
        practical_example: "Obligation Hertz 2020 (valeur nominale $100) → trading à $20 pendant la faillite. Les fonds distressed achètent à $20, négocient la restructuration, récupèrent $40-50 en nouvelles actions → 100-150% de return.",
      },
      {
        id: 7,
        title: "Multi-strategy et pod structure",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Multi-strat HF", "Pod structure", "Capital allocation", "Cross-margining", "Citadel / Millennium"],
        practical_example: "Citadel Multi-Strat : 26% de retour en 2022 pendant que tout perdait. La structure en 'pods' indépendants avec strict risk limit par pod évite les corrélations catastrophiques. C'est le modèle HF le plus copié au monde.",
      },
      {
        id: 8,
        title: "Gérer l'alpha et le reporting",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Alpha vs Beta", "Factor exposure", "Attribution de performance", "Investor reporting", "GIPS standards"],
        practical_example: "Un HF qui performe +20% quand le marché fait +18% n'a généralement pas d'alpha. Un HF +20% quand le marché fait 0% (beta neutre) — là c'est de l'alpha pur. La distinction est cruciale.",
      },
      {
        id: 9,
        title: "Quiz — Stratégies Hedge Funds",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif HF strategies"],
        practical_example: "Teste ta compréhension des stratégies institutionnelles.",
      },
    ],
  },

  {
    id: "risk-management-pro",
    title: "Risk Management Professionnel",
    level: "avancé",
    duration: "1h45",
    chapters_count: 8,
    icon: "⚖️",
    description: "VaR, Sharpe ratio, drawdown, corrélations — gérer le risque comme un institutionnel",
    video_intro: "https://www.youtube.com/embed/Z7GiZR5Dvjk",
    chapters: [
      {
        id: 1,
        title: "Value at Risk (VaR)",
        duration: "12 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/Z7GiZR5Dvjk",
        key_concepts: ["VaR paramétrique", "VaR historique", "Monte Carlo VaR", "CVaR/Expected Shortfall", "Backtesting VaR"],
        practical_example: "VaR 95% à 1 jour de $1M : il y a 5% de chances de perdre plus de $1M en une journée. En 2008, la VaR des grandes banques se trompait systématiquement — les queues de distribution sont épaisses.",
      },
      {
        id: 2,
        title: "Sharpe, Sortino, Calmar — les métriques clés",
        duration: "11 min",
        type: "lecture",
        key_concepts: ["Sharpe ratio", "Sortino ratio", "Calmar ratio", "Information ratio", "Max drawdown"],
        practical_example: "Sharpe 1.5 = très bon en gestion institutionnelle. Renaissance Medallion Fund : Sharpe estimé à 2.5+ (avant frais). La plupart des gérants actifs ont un Sharpe < 0.5 en réalité, inférieur à un simple ETF.",
      },
      {
        id: 3,
        title: "Matrices de corrélation et diversification",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Corrélation de Pearson", "Matrix de covariance", "Diversification Markowitz", "Portefeuille efficient", "Corrélation en crise"],
        practical_example: "2008 : corrélations de tous les actifs risqués convergent vers 1. La diversification 'disparaît' pendant les crises (on l'appelle 'correlation breakdown'). L'or et les Treasuries sont les seuls vrais diversificateurs.",
      },
      {
        id: 4,
        title: "Stress testing et scenarios",
        duration: "11 min",
        type: "video",
        video_url: "https://www.youtube.com/embed/sMIHl-wKzAA",
        key_concepts: ["Historical stress test", "Hypothetical scenario", "Reverse stress test", "Tail risk hedging"],
        practical_example: "Stress test : 'Que se passe-t-il si on revit 2008 ?' Appliquer les chocs historiques (actions -45%, crédit +400bps, VIX +200%) au portefeuille actuel. Si la perte potentielle est inacceptable, réduire l'exposition.",
      },
      {
        id: 5,
        title: "Risque de liquidité et de contrepartie",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Liquidity risk", "Funding liquidity", "Counterparty risk", "Margin call", "Prime brokerage"],
        practical_example: "LTCM 1998 : Sharpe historique de 4.5, stratégies brillantes, mais 25:1 de levier. Quand les marchés ont divergé, les margin calls ont forcé la vente en catastrophe. $4.6B de perte, sauvetage de la Fed.",
      },
      {
        id: 6,
        title: "Gestion des drawdowns",
        duration: "10 min",
        type: "lecture",
        key_concepts: ["Drawdown psychologie", "Réduction d'exposition en drawdown", "Kelly criterion", "Compound return", "Time to recovery"],
        practical_example: "Règle Kelly optimisée : bettor avec 60% de wins et R/R 2:1 → Kelly = 40% du capital par trade. Trop agressif → Half-Kelly (20%) pour survivre aux séries de pertes. Le Kelly complet peut détruire un compte.",
      },
      {
        id: 7,
        title: "Réglementation et conformité",
        duration: "9 min",
        type: "lecture",
        key_concepts: ["Bâle III", "EMIR", "Dodd-Frank", "Reporting réglementaire", "Limites de position"],
        practical_example: "Bâle III impose aux banques un ratio CET1 de 4.5% minimum. En 2008, certaines banques avaient 2%. Ces règles post-crise ont rendu le système plus solide mais ont aussi réduit la liquidité de marché.",
      },
      {
        id: 8,
        title: "Quiz — Risk Management Pro",
        duration: "5 min",
        type: "quiz_only",
        key_concepts: ["Récapitulatif risk management institutionnel"],
        practical_example: "Teste ta maîtrise du risk management professionnel.",
      },
    ],
  },
]

// ─── Helpers ──────────────────────────────────────────────────────────────────

export function getCourse(id: string): Course | undefined {
  return COURSES.find(c => c.id === id)
}

export function getTotalChapters(): number {
  return COURSES.reduce((sum, c) => sum + c.chapters.length, 0)
}

export const LEVEL_COLORS = {
  débutant:      { bg: "rgba(74,222,128,0.1)",  text: "#4ade80", border: "rgba(74,222,128,0.25)"  },
  intermédiaire: { bg: "rgba(96,165,250,0.1)",  text: "#60a5fa", border: "rgba(96,165,250,0.25)"  },
  avancé:        { bg: "rgba(167,139,250,0.1)", text: "#a78bfa", border: "rgba(167,139,250,0.25)" },
}

export const LEVEL_ORDER = { débutant: 0, intermédiaire: 1, avancé: 2 }
